### ISSUE TITLE
Integer encoding for categorical variables in random forests in R

### ISSUE THREAD

**Issue by zachmayer** [szilard/benchm-ml#22]
This quote stuck out to me: 

> It cannot cope by default with a large number of categories, therefore the data had to be one-hot encoded.

Did you try integer-encoding categories?  It looks like you did for python, maybe that's worth trying with R.

**Comment by szilard** [comment]
Yes, I played around, see the discussion here https://github.com/szilard/benchm-ml/issues/1

**Comment by szilard** [comment]
Closing this, but let me know if you have further questions.
