### ISSUE TITLE
benchm-ml/z-other-tools/4-h2o.R change in import format

### ISSUE THREAD

**Issue by tobigithub** [szilard/benchm-ml#41]
Hi, 
for   H2O cluster version:        3.8.3.3 
the import function in benchm-ml/z-other-tools/4-h2o.R should be corrected to

``` R
dx_train <- h2o.importFile(path = "train-1m.csv")
```

otherwise the following error occours

``` R
> dx_train <- h2o.importFile(h2oServer, path = "train-1m.csv")
Error: is.character(key) && length(key) == 1L && !is.na(key) is not TRUE
```

Cheers
Tobias

**Comment by szilard** [comment]
OK, done as z-other-tools/4-h2o-v3.R
Thanks
