### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by dirmeier** [szilard/benchm-ml#57]
Hey, 
thanks for this repository.  It's tremendously useful. Would it be possible to maybe add info on how to cite this repository? Maybe sth like:

```
@misc{,
	author = {Pafka, Szilard},
	title = {benchm-ml},
	publisher = {GitHub},
	year = {2019},
	journal = {GitHub repository},
	howpublished = {\url{https://github.com/szilard/benchm-ml}},
	commit = {13325ce3edd7c902390197f43bcc7938c306bbe3}
}
```
Best,
Simon

**Comment by szilard** [comment]
Sure, thanks @dirmeier, can you make a pull request? (not sure where this would go the best, maybe the end of the README?)
