### ISSUE TITLE
Add Rborist

### ISSUE THREAD

**Issue by eddelbuettel** [szilard/benchm-ml#6]
Could you add [Rborist](http://cran.rstudio.com/web/packages/Rborist/index.html) in serial and parallel mode to add another (fast?) random forest implementation?

Great project. Very useful to have comparisons.

**Comment by szilard** [comment]
I actually tested that, but it was slower (160sec) than R's randomForest package (50sec) on the smallest 10K data even in parallel mode (it was using all 32 cores).

**Comment by eddelbuettel** [comment]
Thanks for the follow-up. I will ask Mark about it; he will be here for R/Finance in a few weeks.
