### ISSUE TITLE
Is it better to consider generating sparse matrix in R?

### ISSUE THREAD

**Issue by hetong007** [szilard/benchm-ml#7]
As far as I know, using `model.matrix` is generating a dense matrix https://github.com/szilard/benchm-ml/blob/master/2-rf/1.R#L16 which is extremely memory inefficient. 

The `glmnet` package in R can do linear regression on top of sparse matrix. I guess `H2O` can handle sparsity really well so it never crashes. If we can also have the result with the sparse matrix, then it is getting fairer and more meaningful.

**Comment by szilard** [comment]
Well, linear models are not really the main focus of this study (due to lower accuracy), but if you rewrite the code with SparseMatrix and send me the code and timings, I'll be happy to include your findings.

**Comment by hetong007** [comment]
Another reason to argue this is `xgboost` also supports sparse matrix input. I will send you the code with this transformation soon. 

One thing is I am not working on a decent machine so probably I cannot test the code with too large data sets. I hope there's nothing happening in the transformation process on them.

**Comment by szilard** [comment]
Merged your code, re-ran results, updated docs. Thanks for the tip/code with sparse matrix.
